import { NAME } from "./constants";

export const FETCH_PRODUCTS = `${NAME}.FETCH_PRODUCTS`;
export const FETCH_PRODUCTS_SUCCESS = `${NAME}.FETCH_PRODUCTS_SUCCESS`;
export const FETCH_PRODUCTS_FAILURE = `${NAME}.FETCH_PRODUCTS_FAILURE`;

export const TOGGLE_FAVORITE_PRODUCT = `${NAME}.TOGGLE_FAVORITE_PRODUCT`;
export const UPDATE_PRODUCT_CART_COUNT = `${NAME}.UPDATE_PRODUCT_CART_COUNT`;
